### ISSUE TITLE
Add support for famous package managers

### ISSUE THREAD

**Issue by cryptus-neoxys** [kvssankar/git-ultimate-cloner#23]
Add in support for various package managers:

- [x] Add support for Go
- [x] Add support for Dart
- [x] Add support for Rust
- [x] Add support for Ruby
- [x] Add support for PHP
- ~~Add support conda pkg manager~~
- ~~Add support for Java~~

**Comment by cryptus-neoxys** [comment]
> Yup assigned, we are also looking to add support for different package managers, rn it supports:
> 
> 1. npm
> 2. pip
> 
> do suggest any other famous ones which are needed

Can I add in more issues language-wise for popular package managers?

**Comment by Tanmay000009** [comment]
Hey, @cryptus-neoxys please wait till tonight as we have some updates coming in and restructuring the codebase.😊
