### ISSUE TITLE
!Refactor code base

### ISSUE THREAD

**Issue by Tanmay000009** [kvssankar/git-ultimate-cloner#30]

**Comment by kvssankar** [comment]
whats the status with this @Tanmay000009

**Comment by kvssankar** [comment]
The first priority is adding support for all packages and custom name tags. Then we can convert to commader.js, i will be taking care of this issue myself

**Comment by cryptus-neoxys** [comment]
> The first priority is adding support for all packages and custom name tags. Then we can convert to commader.js, i will be taking care of this issue myself

any updates on this?

**Comment by kvssankar** [comment]
Rn nothing
